### ISSUE TITLE
IllegalArgumentException: The value for key %s can not be null

### ISSUE THREAD

**Issue by t-beckmann** [axelspringer/polymorphia#10]
Great library when coding against the new MongoDB driver! Just a minor issue to report when dealing with raw BSONs.

The `SimpleMapTypeCodec` seems to be broken when decoding a BSON `null` value. The BSON `null` is decoded as a Java `null` and passed on to `org.bson.BsonDocument.put(String, BsonValue)` which throws an `IllegalArgumentException` when encountering Java `null` values.

I think the correct fix is to use `org.bson.BsonNull.VALUE` in place of Java `null` here: https://github.com/axelspringer/polymorphia/blob/c003be2702e48441a0619e7a4733b51194fdb06d/src/main/java/de/bild/codec/SimpleMapTypeCodec.java#L32

**Comment by webermich** [comment]
Hi Thomas,

thanks for using polymorphia and trying to improve it!

`SimpleMapTypeCodec`'s intention is to encode/decode ordinary Java maps.
Most java map implementations allow to put Null-values into. 
The specialized map `BsonDocument extends BsonValue implements Map<String, BsonValue>, Cloneable, Bson, Serializable` does not allow null. Instead a placeholder `BsonNull.VALUE` must be used.

If every Null-map-value would be decoded as `org.bson.BsonNull.VALUE` this would be quite unexpected by the consumer of that map especially since most maps to be decoded are not `BsonDocument`

`SimpleMapTypeCodec` is not the correct codec to use to decode a property of type BsonDocument. Since most codecs (also those provided by mongo driver project)
are incapable of decoding Null correctly the `SimpleMapTypeCodec` handles that and in most cases it works.

Now the `org.bson.codecs.BsonDocumentCodec` handles Null values when decoding and creates `org.bson.BsonNull.VALUE` for such.

If you can make sure to chain the `org.bson.codecs.BsonDocumentCodec` before the `PojoCodecProvider` in your `CodecRegistry` setup you should be done.

Try chaining the mongo default codecs first like:
`        public static CodecRegistry getCodecRegistry() {
            return CodecRegistries.fromRegistries(
                    MongoClient.getDefaultCodecRegistry(),
                    CodecRegistries.fromProviders(
                            new EnumCodecProvider(),
                            PojoCodecProvider.builder().register("com.xyz.abc").build()
                    )
            );
        }
`

Let me know, if that works for you.
If you need to keep your current Codec-order try adding `CodecRegistries.fromCodecs(new BsonDocumentCodec())` to the top of your registry creation.

**Comment by t-beckmann** [comment]
Your argument makes perfect sense!

Therefore I'd love to change the order getting the defaults into first place but some of my classes to be handled by Polymorphia implement `Iterable`. This causes `org.bson.codecs.IterableCodec` to be picked up for them, trying to start with an array for those and failing: org.bson.BsonInvalidOperationException: A StartArray value cannot be written to the root level of a BSON document. So Polymorphia must stay in first place and changing the order does not work unless altering my domain classes.

Actually I already worked around the issue by coding things differently, so that there is no test causing the error, still. Nevertheless I think transcoding BsonDocument should work for me. Therefore to avoid running into issues in the future, I follow your suggestion and add the standard `BsonDocumentCodec` to the top. This works perfectly fine.
