### ISSUE TITLE
Null still showing up for Lists

### ISSUE THREAD

**Issue by jklee14** [axelspringer/polymorphia#7]
Class A {
.....
	@EncodeNulls(false)
	private List<TransDO> transList = null;
....
}

Even if transList is null, it still shows up in the document when inserted into Mongo.
I also did it in the registry and the same result.
My understanding would be that like other variables, it doesn't show up in the Mongo document if the value is null.

![translist](https://user-images.githubusercontent.com/10777188/40845367-7bfb7166-6584-11e8-82a0-2962f61f5902.png)

Am I not doing something correctly or my understanding is wrong? If so how do I not include transList if it's null like the other objects?

Thanks!

**Comment by webermich** [comment]
Hi @jklee14 ,
sorry for the late reply. I somehow didn't get noticed about your raised issue.
Could you provide the polymorphia version you have used?  

About your field "transList": This PojoCodec is not capable to handle non-generic fields of List, Set or Map properly at the moment, when used within Pojos.

I am actually surprised that your given example actually wrote something into the database instead of throwing an exception. I would expect something like "org.bson.codecs.configuration.CodecConfigurationException".
Did you chain org.bson.codecs.IterableCodec before the PojoCodec when creating your CodecRegistry? Would be interesting to get more details about your setup.

To solve your problem you have two options:
1) use a generic List eg. List<SomeOtherPojo>
2) use @de.bild.codec.annotations.Transient at you field if you don'T wnat that field stored to the database at all (somehow the name "transList" migh imply to me it is a transient list)

**Comment by webermich** [comment]
I now have added suport for non generic Lists, Sets and Maps within Pojos.
I still do not understand your setup. 
Additionally your screen shot implies that your field "transList" was not `null` as an `Array` was wriiten to the database.

Have a look at 
https://github.com/axelspringer/polymorphia/blob/3676effdc5a8c5c8fe58e8b1ddf04ecb4bfdb94d/src/test/java/de/bild/codec/NullHandlingTest.java#L84

This is a working example of what you need to achieve, I think?!

I will close this ticket. Let me know, if you need furhter support.

**Comment by jklee14** [comment]
Hi From the looks of  your comment, I think you may have addressed my issue!
Thank you, let me try.

transList may or may not be null, and if it's null, we don't want it to appear in MongoDB which takes up space.

Polymorphia is working well for you, Thank you.

**Comment by jklee14** [comment]
Everything is work as it should thank you so much for your support!
